### ISSUE TITLE
Z Probe depth until fail

### ISSUE THREAD

**Issue by manuel1139** [kreso-t/cncjs-kt-ext#57]
Hi, I have a question about this line
  
  code.push(`G38.2 Z-${this.height + 1} F${this.feed / 2}`)

This pushes the Z-probe  Z-3 before the probe fails and even worse if you increase the height  the probe will even get worse until the probe fails. For safety I would like to create the test height map for about max. 0.3 mm. So what is the intended idea about this line?

Best Regards,
Manuel

**Comment by kreso-t** [comment]
Hi, 
Not quite sure what you mean by "probe fails" - if you mean that probe does not detect contact with material when actually there is a contact then probe HW is faulty and should be fixed.  If probe HW is OK then this line would push the probe slowly into material until probe send signal that contact with material has detected, then the move is automatically stopped and zero Z=0 is set (by G10 L20 P1 Z0).   If material is not contacted before target Z is reached (i.e. Z-3) then grbl reports that probing has failed. So in order for probing not to fail zero point should already be set before running auto-level (so that at starting point Z=0 is aprox. when probe is touching material) and this max probing depth (Z-3) should be large enough.

You can't limit the height map currently, if probing depth is not large enough for all points autolevel will fail.

Hope this helps
BR,
Kresimir
